### PR TITLE
Added to "Pod Style" Seat Alias whitelist

### PR DESCRIPTION
**Pull request by bluemetaknight**
Fixes https://github.com/ACF-Team/ACF-3/issues/417

Adds the other "Pod" style seats to the "Pod" style hitbox whitelist for seat Aliases.

### CODE REVIEW

**Comment by thecraftianman** [comment]
This change seemingly doesn't do anything? I've tested all the affected seats before and after, and this doesn't actually change their hitbox.
image

**Comment by bluemetaknight** [comment]
https://github.com/user-attachments/assets/912cae5b-ea26-4fc7-be35-e6038223ca1c

Im fairly certain it works, I did have to reload my game between changes.

The bug seems to happen on dupes that have been saved, then re-opened. Holding a dupe in the tool gun maintains the proper hitbox, but saving that dupe, then respawning it causes it to fail. The above fixes resolved that issue. This was tested on a peer to peer however, so it may be different for an actual server.

**Comment by bluemetaknight** [comment]
I will also note that the pronepose playerstart chair seems to have a misaligned player alias, though I will leave that to LiddulBOFH resolve when he gets the opportunity, as I have no idea how he figured out the alignment for all the seats.

**Comment by LiddulBOFH** [comment]
There have been many annoyances regarding vehicles that really come to light with this system, such as the table tied to vehicles that define what they are just not getting defined post-dupe, meaning the data has to be retrieved by alternative means; and even that doesn't seem to be a consistent thing; that, paired with an actually solid vehicle entity that is just good to work with, makes anything attempting to work with them absolute pain.
We've joked with the idea of just making an entirely lua-based vehicle entity that we get absolute control over how they work and how they are made, just to fix all of the shortcomings that seats have right now, and every day I see a new issue pop up with these alias entities I think about it more.

**Comment by bluemetaknight** [comment]
Fixed on dev branch.

**Pull request closed without merging**
