### PR TITLE
Replace ACT_GMOD_SIT_ROLLERCOASTER with ACT_HL2MP_SIT animation on playerstart chairs

### PR DESCRIPTION
**Pull request by sigurdjoergensen**
Replaces the rollercoaster animation of playerstart chairs with the HL2MP_SIT animation. This makes the playermodel actually stay inside the hitbox and avoids hands and feet sticking out from the armor. The chairs without rollercoaster animation are left alone. It's done in the same way as Garry's Mod does it: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/autorun/base_vehicles.lua

### CODE REVIEW

**Comment by sigurdjoergensen** [comment]
image
new problem, characters are sitting a bit above the hitbox. i dont know if this is worse or can be easily fixed

**Comment by sigurdjoergensen** [comment]
image
I tried the vehicle_feet_passenger of the model but this breaks the physics completely, i give up B-)

**Comment by TwistedTail** [comment]
So far, I can't seem to find any built-in way to move the driver around. The only option in this case would be manually moving around the player after they enter the seat (Unparent, move, parent), but I assume that will have other complications arise. Personally I don't think it's worth the effort.

**Comment by sigurdjoergensen** [comment]
I moved the position of the playermodel by changing the vehicle_feet_passenger0 attachment in the decompiled models coordinate from 20 to 17 in the up down axis, and to fix the collison model being rotated from the actual visual model, i just kept old physics model as it breaks on compilation for some reason. The player model is still slighly misaligned from the wireframe, but thats because of the pose itself and the entire chair model would have to be changed to fix that. here are pictures:
hl2_6Nyxy9874W
hl2_wu7ZGQHPLO

**Comment by thecraftianman** [comment]
Could you remove the conflicting model files from this?

**Comment by TwistedTail** [comment]
> Could you remove the conflicting model files from this?

@sigurdjoergensen This is pretty much the only thing required to have this PR approved and merged.

**Comment by sigurdjoergensen** [comment]
Was this what you wanted?

**Pull request merged**
